Database:
  Cache: "false"
  ConnMaxLifTime: 1h
  Database: "homa"
  Debug: "3"
  Enabled: true
  MaxIdleConns: 10
  MaxOpenConns: 100
  Params: "parseTime=true"
  Password: "password"
  SSLMode: false
  Server: 127.0.0.1:3306
  SlowQueryThreshold: 500ms
  Type: mysql
  Username: username
HTTP:
  BodyLimit: 25mb
  CaseSensitive: false
  CompressedFileSuffix: .evo.gz
  Concurrency: 1024
  DisableDefaultContentType: false
  DisableDefaultDate: false
  DisableHeaderNormalizing: false
  DisableKeepalive: false
  ETag: false
  GETOnly: false
  Host: 0.0.0.0
  IdleTimeout: 0
  Immutable: false
  Network: ""
  Port: 8000
  Prefork: false
  ProxyHeader: X-Forwarded-For
  ReadBufferSize: 10mb
  ReadTimeout: 1s
  ReduceMemoryUsage: false
  ServerHeader: EVO
  StrictRouting: false
  UnescapePath: false
  EnablePrintRoutes: false
  WriteBufferSize: 4kb
  WriteTimeout: 5s
JWT:
  SECRET: "CHANGE-THIS-IN-PRODUCTION-USE-STRONG-SECRET-AT-LEAST-32-CHARS"
OAUTH:
  GOOGLE:
    ENABLED: false
    CLIENT_ID: ""
    SECRET: ""
  MICROSOFT:
    ENABLED: false
    CLIENT_ID: ""
    SECRET: ""
APP:
  BASE_PATH: "http://localhost:8000"